<?php

namespace App\Models;

use App\Jobs\SendNotificationJob;
use App\Traits\NotificationsTrait;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class Notification extends Model
{
    use NotificationsTrait;

    protected $fillable=[
        'notificationable_id',
        'notificationable_type',
        'user_id',
        'grouped_users',
        'title',
        'description',
        'idClasse',
    ];

    public function notificationable(){
        return $this->morphTo();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($notification){
            //On ajoute plutôt un job qui va envoyer les notifications
            SendNotificationJob::dispatch($notification); //->delay(now()->addMinutes(1));

//            $notification->sendMobileNotificationViaNotificationsTrait();
//            $notification->sendWebOrMobileNotification('mobile', true);
        });
    }

//    public static function sendWebNotification($data, $single_user = true){
//
//    }

    // Ajout d'un scope pour les notifications d'un utilisateur spécifique
    public function scopeForUser(Builder $query, $userId)
    {
        return $query->where('user_id', $userId)
            ->orWhereJsonContains('grouped_users', $userId);
    }
}
